### ISSUE TITLE
Memory leak (cannot read properties of null removeObservers)

### ISSUE THREAD

**Issue by blahbleepew** [YousefED/reactive#11]
I'm having issues with removeObservers being called on a null value. the component it's being used in is being dropped and removeObservers gets called on a null value.

```
react-dom.development.js:22839 Uncaught TypeError: Cannot read properties of null (reading 'removeObservers')
    at useReactive.ts:30:24
    at safelyCallDestroy (react-dom.development.js:22932:5)
    at commitHookEffectListUnmount (react-dom.development.js:23100:11)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (react-dom.development.js:25098:11)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (react-dom.development.js:25048:5)
    at commitPassiveUnmountEffects_begin (react-dom.development.js:24956:11)
    at commitPassiveUnmountEffects (react-dom.development.js:24941:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27038:3)
    at flushPassiveEffects (react-dom.development.js:26984:14)
    at performSyncWorkOnRoot (react-dom.development.js:26076:3)
```

affected code:

```
    return () => {
      mounted.current = false;
      observer.current.removeObservers();
      observer.current = null;
    };
```

I assume an `observer.current?.removeObservers()` would suffice but I'm having trouble getting a patch/install working

**Comment by blahbleepew** [comment]
mislabeled the title, meant dangling reference, but observer.current? does fix the problem (I was forgetting to patch both lines)

**Comment by blahbleepew** [comment]
wrong title, meant a dangling reference, but using a patch to replace every method call with 

`if (observer.current !== undefined && observer.current !== null) observer.current.removeObservers()`

fixed my problem

**Comment by YousefED** [comment]
Thanks @blahbleepew ,

Do you perhaps have a way to reproduce this issue? For example using CodeSandbox?

**Comment by austinbuckler** [comment]
I ran into this issue as well (using `@syncedstore/react`), I can see if I can try to reproduce in an isolated environment.

I am using slate, and attached a key to the slate editor. The children nodes inside the slate editor got dropped (due to external state changing) and the children were unable to remove the observers.

**Comment by YousefED** [comment]
> I ran into this issue as well (using @syncedstore/react), I can see if I can try to reproduce in an isolated environment.

Thanks @austinbuckler, this would definitely be useful!

**Comment by Dammic** [comment]
Hey! I got the same problem as written above, also using `@syncedstore/react` (though we don't use any editor)

We have a hmr set up in the application (using CRA react-scripts 5.0.1) and basically everytime there is any update in the code and the page is about to be refreshed with HMR, the page crashes with that error for every place that uses `useSyncedStore` (so it throws a lot of errors for us). That is present only in development, but is a bit annoying nonetheless.

We have a bit of specific way of using the useSyncedStore - we have a context that preserves the 'store' (with some extra logic) and everywhere we want to access it, we use this useSyncedStore.

I've tried to reproduce it with the official example, but somehow there it doesn't crash.
I will try to reproduce it with some other example that can be shared.

**Comment by Dammic** [comment]
I wasn't able to reproduce it yet with any simple example, but I have some observations:
- it happens only in strict mode, which means there is quick mount/unmount thing going on,
- I was able to get this problem in some other case - when navigating to page that uses syncedStore (from a page that doesn't). It seems that if it happens, it happens consistently, but it doesn't happen in all flows for some reason. This makes me think that it might be problem when there is a lot of nesting between creating a store and using it (so deeper rendering logic).

My current theory is that the code https://github.com/YousefED/reactive/blob/main/packages/reactive-react/src/useReactive.ts#L28 is called before https://github.com/YousefED/reactive/blob/main/packages/reactive-react/src/useReactive.ts#L10 due to some unmounting update that interrupts rendering. It is very strange.

Or the unmount useeffect is called twice https://github.com/YousefED/reactive/blob/main/packages/reactive-react/src/useReactive.ts#L59
(so it mounts, unmounts and then mounts and then unmount, which cause the problem?)

With that in mind, would it be possible to add this extra safety check for this part of the code (like the one mentioned above), or would you prefer to have a solid reproduction? Unfortunately it's not easy for me to create a simple case that reproduces that, as this seems to be more intricate.

Thanks at lot in advance!

**Comment by Dammic** [comment]
Hey! I was able to reproduce it with the example from the repository of syncedstore. It's a pretty weird way and obviously an overkill, but when you run the sandbox for a couple of seconds, you will get this exact error thrown at some point.
https://codesandbox.io/s/empty-water-pgjqhd?file=/src/index.tsx
(though you need to add a couple of todos from what I see)


https://user-images.githubusercontent.com/18100361/220895341-fcc9540a-aac3-4c3d-92ae-080d433cc51a.mp4

**Comment by Dammic** [comment]
hey @YousefED sorry for the ping, but have you perhaps have had a chance to look at this example I provided above?

**Comment by YousefED** [comment]
I've implemented the suggested fix. It's difficult to diagnose exactly, seems like the React order is not completely deterministic. Hopefully the fix solves your issues!

**Comment by Dammic** [comment]
Nice! I've just tried it and it resolved the issue on our side. Thanks a lot, you're the best!

One small note - I had to do some small pnpm overriding because `syncedstore` seems to still pull `@reactivedata/react` 0.2.1 instead of 0.2.2
