### ISSUE TITLE
[Question] Can we share the state between React components

### ISSUE THREAD

**Issue by echarles** [YousefED/reactive#5]
Hi, I wonder if the goal of this library is to share the state between different React components?

For now, I see `useReactive` hook which makes me think to `userState` but don't see something similar to the Redux hooks that allow one component to access store defined by another component, eg:

- useStore https://react-redux.js.org/api/hooks#usestore
- useSelector https://react-redux.js.org/api/hooks#useselector

**Comment by YousefED** [comment]
Hi @echarles ,

What you can do, is define a global store somewhere:

```
export const globalStore = reactive({
  players: [{ name: "Peter" }],
});
```

You can then use this in your react components using `useReactive(globalStore)`.

_tip_: If you don't like to export global stores (for example, because of testability), you can of course use React Context and create a StoreContextProvider for a little cleaner design.

**Comment by echarles** [comment]
Works as expected. Thx @YousefED
