### ISSUE TITLE
useReactive breaking in React 18

### ISSUE THREAD

**Issue by TudorZgimbau** [YousefED/reactive#8]
Reactive-react lists React 17 in devDependencies. Using it in a React 18 app(for example, with SyncedStore) breaks it because there are 2 different versions of React in node_modules (generically throws "incorrect use of React hooks" type of error). Removing the installed React dependency fixes the problem.

**Comment by lstwn** [comment]
I face the same issue, can you tell me how you resolved this exactly? Thanks!

**Comment by TudorZgimbau** [comment]
> I face the same issue, can you tell me how you resolved this exactly? Thanks!

I deleted the react folder from @syncedstore/react/node_modules (this was the 2nd version of react in the same project which caused the trouble). Make sure to check the path as it could differ based on how you installed the dependency. Also, I think that downgrading to React 17 is another way to solve this.

**Comment by lstwn** [comment]
Thanks! Deleting the folder manually did work for me, too. However, this is only a temporary workaround since after every (re)install we need to do this again. Downgrading sucks, too. Looks like updating the peer dependency in this project seems the only real fix.

Unfortunately, I'm new to react and yjs and cannot assess whether an update breaks compatibility (however, my current local tests suggest no issues so far..). That's why I don't feel like submitting a PR here. Let me know if I can help though.

**Comment by TudorZgimbau** [comment]
No problem! Neither do I know if switching to React 18 breaks something, it's up to @YousefED to decide whether the upgrade can be performed safely.

**Comment by TudorZgimbau** [comment]
Thanks for adding support for React 18!

**Comment by YousefED** [comment]
You're welcome! Also updated SyncedStore. The issue was that react 18 was not listed as peerdependency :)
